export enum Items{
    "Fight",
    "Sports",
    "Survival",
    "Horror", 
    "RPG", 
    "Fps", 
    "Tps", 
    "Platform", 
    "Adventure", 
    "Action",
    "Minigame", 
    "Racing",
    "Strategy", 
    "Musical", 
    "Dance",
    "Simulator",
}