export enum Items1{
    "PS", 
    "PS2", 
    "PS3", 
    "PS4", 
    "PS5", 
    "PSP", 
    "XBOX", 
    "XBOX 360", 
    "XBOX ONE", 
    "XBOX SERIES S", 
    "XBOX SERIES X", 
    "SUPER NINTENDO", 
    "NINTENDO 64", 
    "NINTENDO SWITCH", 
    "NINTENDO WII", 
    "NINTENDO DS", 
    "NINTENDO 3DS", 
    "MEGA DRIVE", 
    "PC", 
    "MOBILE",
}